name: se7ty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  device_preview: ^1.3.1
  go_router: ^16.3.0
  smooth_page_indicator: ^1.2.1
  firebase_core: ^4.2.0
  flutter_bloc: ^9.1.1
  firebase_auth: ^6.1.1
  lottie: ^3.3.1
  cloud_firestore: ^6.0.3
  image_picker: ^1.2.0
  gap: ^3.0.1
  google_nav_bar: ^5.0.7
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  generate: true 


  assets:
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
